Feature/tracking
vortexntnu/deprecated-vortex-cv pull request #118
Opened 2023-02-05 14:11 UTC by hannahcl

2023-02-05 20:10 UTC, hannahcl commented
Documentation: http://vortex.a2hosted.com/index.php/CV_target_tracking

2023-02-13 16:09 UTC, chrstrom requested changes

2023-02-13 16:09 UTC, chrstrom commented on .vscode/settings.json
>  }
The entire .vscode folder should be removed methinks 😅

2023-02-13 16:09 UTC, chrstrom commented on tracking/launch/boat_tracking.launch
> +        respawn: true or false depending if you want the node to restart after it dies (usually of some error) -->
This description can be removed

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/boat_tracking_node.py
> +        rospy.Subscriber("lidar_clusters", PoseArray, self.cb)
since the topic name of this subscriber doesn't start with a /, you might run into some namespacing issues if this node or the publishing side is launched as part of a ns. Just in case you run into weird issues later down the road 😄

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/config_traking_sys.yaml
> +
I think this should go in a separate config/ folder

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/pdaf.py
> +    def cb(self, o_arr, time_step):
I think a better name for this method would be "step_once" or something along those lines

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/pdaf.py
> +        return obs
Could these be moved to a separate file? As

```
class PDAFTester(PDAF):
   ...
```

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/plots.py
> +sys.path.insert(0, "/home/hannahcl/Documents/vortex/monkey_tracking/data_generation")
I am not sure where the data generator for tracking should go. It could be an idea to just add the data_generation folder directly to this package. You could then write a setup.py along the lines of

```
#!/usr/bin/python3

from setuptools import setup, find_packages

setup(
    name="",
    version="",
    description="",
    author="",
    author_email="",
    packages=find_packages(),
)
```

which you could either use to manually install the data generator with pip, or add the ```catkin_python_setup()``` line to your CMakeLists.txt for auto install when building the ros package with catkin

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/pdaf.py
> +        self.P_pri = self.P_post  # prior error covariance estimate
It could make sense to create a 

```python
@dataclass
class MultiVariateGaussian:
    mean: "ndarray[:]"
    covariance: "ndarray[:,:]"
    timestamp: float
```
to contain this. It would involve some rewriting of the code here, but if the cleanliness weighs up for the extra work, go ahead 🐱

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/pdaf.py
> +        self.compute_S()
I am 50/50 on maintaining extra state in the PDAF class vs returning matrices and passing them to only the methods that need them. Is there a substantial speed gain by doing it this way?

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/test/test_pdaf.py
> +PATH_TO_CONFIG_TRACKING_SYS = "/home/hannahcl/Documents/vortex/asv_ws/src/vortex-asv/navigation/tracking/scripts"
I dont think this should be kept in here, but I am also not entirely sure how else to get past it 🤷‍♂️ There should definitely be a top level README explaining it though

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/test/test_pdaf.py
> +        config_loaded = yaml.safe_load(stream)
If you make a test fixture

```
class TestPdaf:
    ....
```

that contains this, you would only need one of these calls. All other tests could then use this, as long as you make it a member variable

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/test/test_track_mangager.py
> +pytest test_track_manager.py::test_plot_interactive -s
same as before, think this belongs in a README explaining usage

2023-02-13 16:09 UTC, chrstrom commented on tracking/scripts/track_manager.py
> +                self.main_track.track_status = TRACK_STATUS.tentative_confirm
Just as a note, instead of maintaining just the main_track, you could instead keep a list of all tracks, and have a multi-target tracker based on the single-target assumptions. This would work well as long as no measurements end up in more than one validation gate

2023-02-19 14:04 UTC, hannahcl commented on tracking/scripts/pdaf.py
> +        self.compute_S()
According to Chat GPT there is no obvious better solution. For large objects it "may" be more efficient to modify class instances. So code quality should be priority. 
After using the MultivariateGaussian data class, it seems natural to have all gaussians as class instances, while the kalman gain can be passed as an argument.

2023-02-20 14:44 UTC, chrstrom commented on tracking/scripts/pdaf.py
> +        self.compute_S()
Fair enough, I think this is a fine middle-ground 😸

2023-02-20 14:46 UTC, chrstrom commented on tracking/scripts/test/test_pdaf.py
> +PATH_TO_CONFIG_TRACKING_SYS = "/home/hannahcl/Documents/vortex/asv_ws/src/vortex-asv/navigation/tracking/scripts"
I added an installation step in the monkey tracker repo. You will then be able to do something like

```python
import data_generation as dg


scenario = dg.scenarios.BaseScenario(config)
```

2023-02-20 14:51 UTC, chrstrom commented
Looking very nice 😄 Quick Q: what's the buoy-detection code doing here?

Also: We *finally* have the repository [vortex-sensor-fusion](https://github.com/vortexntnu/vortex-sensor-fusion), and this is perfect to start the tracking/ folder there.................... I know theres a lot of moving code around so maybe leave that to whenever the great cv-repo cleanup comes?

2023-03-05 14:48 UTC, chrstrom commented on tracking/scripts/trackManagerMultipleTracks.py
> +import numpy as np
Using this file to comment on semantics (Not sure if they will be caught by the autoformatter)

1. Filename should use snake_case, i.e. track_manager_multiple_tracks.py.

2023-03-05 14:48 UTC, chrstrom commented on tracking/scripts/trackManagerMultipleTracks.py
> +class TRACK_STATUS(Enum):
Classes should follow CamelCase

2023-06-17 11:14 UTC, merged