Feature/aruco
vortexntnu/deprecated-vortex-cv pull request #127
Opened 2023-06-16 11:20 UTC by EirikKolas

# ArUco Detection done
- Detect markers and print ids
- Estimate pose of ArUco Board
- Tunable image filtering for better detection with `rqt_reconfigure`
- OpenCV 4.2.0 added to dockerfile
- Modified vkf to work with ArUco detection

2023-06-17 11:49 UTC, theBadMusician requested changes
As this has been tested and worked during TAC Challenge, we know that it is functionally viable. There are however a some artifacts left over from the rapid prototyping and testing phase that should be fixed.

2023-06-17 11:49 UTC, theBadMusician commented on vision_kf/scripts/vkf_node.py
> +        self.child_frame = 'odom'
Is this supposed to be odom to odom transform? Why?

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/include/aruco_detection_node.hpp
> +// #include <opencv2/imgproc.hpp>
Remove if not used

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/include/aruco_detection_node.hpp
> +// #include <vortex_msgs/LandmarkPose.h>
remove commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/include/aruco_detection_node.hpp
> +	// ros::Publisher opPosePubTfLandmark; //Moved to vision_kf
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/include/aruco_handler.hpp
> +// #include <Eigen/Geometry>
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/launch/docking.launch
> +    <!-- <node pkg="tf2_ros" type="static_transform_publisher" name="base2dvl"  args="0 0 1 0 0 0 base_link dvl_link" /> For testing only!! -->
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/launch/docking.launch
> +    <node pkg="tf2_ros" type="static_transform_publisher" name="udfc_link_to_aruco_udfc" args="0 0 0 0 1.57079632679 0 udfc_link udfc_aruco_link"/>
This should be fixed in code, so that using the actual camera TF (meaning UDFC pos x pointing down in relation to base_link) the aruco node outputs correct final pose.

As this technically works, and has been tested during TAC, we can leave it for now. However a new issue should be opened regarding this, and fixed properly in the future.

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/package.xml
> +  <!-- <maintainer email="jane.doe@example.com">Jane Doe</maintainer> -->
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/package.xml
> +  <!--   BSD, MIT, Boost Software License, GPLv2, GPLv3, LGPLv2.1, LGPLv3 -->
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/package.xml
> +  <!-- The export tag contains other, unspecified, tags -->
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/package.xml
> +    <!-- Other tools can request additional information be placed here -->
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/src/aruco_detection_node.cpp
> +	// double k1=-0, k2=0, p1=0, p2=0, k3=0;
This code should be made into rosparams or other parametrization platform, as needing to uncomment and comment out different parts of code to choose correct parameters for the camera is scuffed AF.

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/src/aruco_detection_node.cpp
> +	// opObjPubODOM = node.advertise<vortex_msgs::ObjectPosition>("object_positions_in", 100); // this publisher has been moved moved to vision_kf
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/src/aruco_detection_node.cpp
> +	// board = arucoHandler.createRectangularBoard(.167, .462, .862, dictionary, {28, 7, 96, 19}); // Vortex Docking plate dimensions
make into rosparams - same reason as for cam params above.

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/src/aruco_detection_node.cpp
> +
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/src/aruco_handler.cpp
> +	//  cv::solvePnP();
rm commented out code or make into TODO for future work

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/src/aruco_id_node.cpp
> +	// ROS_WARN("More than one id detected!");
rm commented out code or mark as TODO

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/src/aruco_id_node.cpp
> +	// 	return; // No new id detected
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/test/test_aruco_handler.cpp
> +	// arucoHandler.detectMarkers(img, corners, ids, rejected);
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/test/test_aruco_handler.cpp
> +	// ROS_INFO_STREAM("num ids: " << markernum);
rm commented out code

2023-06-17 11:49 UTC, theBadMusician commented on aruco_detection/test/test_aruco_handler.cpp
> +	// testBoardCreator();
if the program does not run anything, should it even exist??

2023-06-17 12:18 UTC, EirikKolas commented on vision_kf/scripts/vkf_node.py
> +        self.child_frame = 'odom'
Yes. The pose from the board detector is published in odom, and the vkf just uses an identity matrix as the model. Wether it "should" be this way is another question. It was Ivan who made the vkf adjustments for aruco_detection

2023-06-17 12:24 UTC, EirikKolas commented on aruco_detection/src/aruco_id_node.cpp
> +	// 	return; // No new id detected
Commented in instead. This was used during pipeline following to ensure unique ids were saved to file.

```suggestion
	// Ignore duplicate ids
	if (std::find(storedIds.begin(), storedIds.end(), foundId) != storedIds.end())
```

2023-06-17 12:26 UTC, EirikKolas commented on aruco_detection/src/aruco_id_node.cpp
> +	// 	return; // No new id detected
was commented out for the visual inspection task as there could be duplicates there

2023-06-17 12:38 UTC, EirikKolas commented on aruco_detection/test/test_aruco_handler.cpp
> +	// testBoardCreator();
yeah.. These functions are a bit outdated anyway. Should I just remove them?

2023-06-17 12:51 UTC, EirikKolas commented on aruco_detection/launch/docking.launch
> +    <node pkg="tf2_ros" type="static_transform_publisher" name="udfc_link_to_aruco_udfc" args="0 0 0 0 1.57079632679 0 udfc_link udfc_aruco_link"/>
Made an issue #128

2023-06-17 14:37 UTC, EirikKolas commented on aruco_detection/src/aruco_detection_node.cpp
> +	// double k1=-0, k2=0, p1=0, p2=0, k3=0;
wouldn't it be cleaner if the parameters were published by the udfc? (like they are in the zed wrapper)

2023-06-17 14:49 UTC, EirikKolas commented on aruco_detection/src/aruco_detection_node.cpp
> +	// board = arucoHandler.createRectangularBoard(.167, .462, .862, dictionary, {28, 7, 96, 19}); // Vortex Docking plate dimensions
For the Njord Challenge, the boards may not neccecarily be rectangular. How would I do the rosparams to be able to switch between different board types? Is it worth it?

2023-06-17 16:47 UTC, theBadMusician commented on vision_kf/scripts/vkf_node.py
> +        self.child_frame = 'odom'
Ok, if it works it works.

Yeah, so the VKF should really be looked into for refurbishments in the future in general - it has a lot of stuff that shouldn't be there; there is much duplicate code; it is super clunky to actually use; and has many more problems in general. An issue should be opened to refactor the VKF into proper OOP structure, as well as implement multi-node support.

2023-06-17 16:48 UTC, theBadMusician commented on aruco_detection/src/aruco_detection_node.cpp
> +	// double k1=-0, k2=0, p1=0, p2=0, k3=0;
Do you mean using the [CameraInfo](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/CameraInfo.html) topic?

2023-06-17 17:00 UTC, theBadMusician commented on aruco_detection/src/aruco_detection_node.cpp
> +	// board = arucoHandler.createRectangularBoard(.167, .462, .862, dictionary, {28, 7, 96, 19}); // Vortex Docking plate dimensions
Well, it is definitely not a good solution to have to uncomment and comment out code. **IF** Njord is going to use something different, we will need to take a look at it then, but it is inefficient to work from assumptions, and it I do not think it is within our scope to create a generalized parametrization for _any_ type of marker.

However, it is certainly not within convention to have to have to change source code to have to change the dimensions of aruco board.

As this does technically work, and has been tested during TAC, this can be set as a new issue, and a new PR opened to fix it, but it should implemented as soon as possible.

2023-06-17 17:02 UTC, theBadMusician commented on aruco_detection/test/test_aruco_handler.cpp
> +	// testBoardCreator();
The question is, in your opinion, is the code valuable enough to be kept in and is it going to be used?

2023-06-17 17:15 UTC, EirikKolas commented on aruco_detection/src/aruco_detection_node.cpp
> +	// double k1=-0, k2=0, p1=0, p2=0, k3=0;
ok, will fix :)

2023-06-17 17:16 UTC, EirikKolas commented on aruco_detection/src/aruco_detection_node.cpp
> +	// board = arucoHandler.createRectangularBoard(.167, .462, .862, dictionary, {28, 7, 96, 19}); // Vortex Docking plate dimensions
Makes sense. Will fix

2023-06-17 17:17 UTC, EirikKolas commented on aruco_detection/test/test_aruco_handler.cpp
> +	// testBoardCreator();
No it's not. Better to make new test code if nececcary. Will remove

2023-06-17 20:42 UTC, EirikKolas commented on vision_kf/scripts/vkf_node.py
> +        self.child_frame = 'odom'
Created issue

2023-06-18 09:55 UTC, theBadMusician approved these changes
LGTM :+1:

2023-06-18 10:00 UTC, merged