Feature/object edc
vortexntnu/deprecated-vortex-cv pull request #54
Opened 2022-03-01 00:35 UTC by ivangushkov

The main development on the vision EKF is done. In connection with the full CV pipeline testing this coming weeks, we should merge this with the main branch. I updated the node and measurement models to better reflect what was achieved on the sim branch, and I streamlined and simplified the code a lot. Would be nice if Krisitan has a look through it, and see if there are any unnecessary definitions (hehe) left in the node. Otherwise Benjamin, please have a look at the structure of the package and say if there is something that needs to change.

#34 
#42

2022-03-21 17:55 UTC, ivangushkov commented
Time estimate: 3 hours
ToDo before merge:

- [ ] Figure out the orientation error on the gate/plane estimation (look into the quaterninon and its w position, I think the VKF thinks w is at position 4 while pointcloud processing puts it at 1.)
- [ ] Change name of package to something that is not object_edc. Suggestions: vkf, object_filtering
- [ ] Change src to scripts
- [ ] Consider removing unnecessary files and folders (python3, the remains of Sensorfusion course etc.)

2022-04-03 13:36 UTC, theBadMusician requested changes
Remove the unused, commented out functions/classes and we're good.

2022-04-03 13:36 UTC, theBadMusician commented on object_edc/ReadMe.txt
> +pip install dataclasses
Change the name of the file to "README.md".

2022-04-03 13:36 UTC, theBadMusician commented on object_edc/ekf_filtering/ReadMe.txt
> +Simple EKF based solution for filtering CV detections of objects like gate and pole. Includes a very general EKF class that admits different process and measurement models, which is the case here. As
Change the name of the file to "README.md".

2022-04-03 13:36 UTC, theBadMusician commented on object_edc/ekf_filtering/ekf/ekf_python2/analysis_py2.py
> +#from typing import Sequence
Remove if not used.

2022-04-03 13:36 UTC, theBadMusician commented on object_edc/ekf_filtering/ekf/ekf_python2/analysis_py2.py
> +#              #TODO
Remove if not being worked on for now.

2022-04-03 13:36 UTC, theBadMusician commented on object_edc/ekf_filtering/ekf/ekf_python2/dynamicmodels_py2.py
> +#        return Q
Needs to be removed if not used, or uncommented if it's something that's useful to have.

2022-04-06 20:55 UTC, theBadMusician approved these changes
Looking good :+1:  
Ready to merge.

2022-04-07 19:20 UTC, merged