Feature/camera calibration
vortexntnu/deprecated-vortex-cv pull request #61
Opened 2022-03-13 12:07 UTC by SimonVolden

Merge feature/camera_calibration with main.

2022-03-14 12:15 UTC, theBadMusician requested changes
Some clean up, documentation, and refactoring needs to be done. See comments.

Why are there object edc files in this branch? All of the non-calibration related changes need to be removed.

2022-03-14 12:15 UTC, theBadMusician commented on .gitignore
> +calibrationdata/
These changes need to be reverted as we do not store calibration data inside the repo any more.

2022-03-14 12:15 UTC, theBadMusician commented on .vscode/launch.json
> +
We don't use this setup any longer. Whole file needs to be removed.

2022-03-14 12:15 UTC, theBadMusician commented on .vscode/settings.json
> +{
We don't use this setup any longer. Whole file needs to be removed.

2022-03-14 12:15 UTC, theBadMusician commented on .vscode/tasks.json
> +{
We don't use this setup any longer. Whole file needs to be removed.

2022-03-14 12:15 UTC, theBadMusician commented on Makefile
> +# CMAKE generated file: DO NOT EDIT!
This isn't used as we utilize Catkin, which handles CMake and Makefiles. File needs to be removed.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/config/camera_calibration.yaml
> +save_config_path: "/home/vortex/vortex_ws/src/Vortex_CV/cv_utils/data/SN38762967CALIBRATED.conf"
There shouldn't be any specific paths. This has to be refactored to use a path agnostic solution, e.g. 'ros params' with  the 'find package' function - point to a directory in a known catkin pkg.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/launch/rosbag_to_jpeg.launch
> +</launch>
The changes need to be reverted, as this isn't camera calibration specific.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +import traceback
Remove the imports that aren't being used.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +    """
Proper class documentation needed.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        # self.zedSub                 = rospy.Subscriber(image_topic, Image, self.camera_callback)
Remove.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        right_img_topic = "/zed2/zed_node/right_raw/image_raw_color"
Needs to be parametrized, so one can easily change the camera which is going to be used for the calibration, e.g. namespace + "left_raw/image_raw_color".

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        self.chessboardSize = (5,7)
The board size should be given as an initialization parameter.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        self.save_config_path = rospy.get_param("/save_config_path")
Mentioned in the comment for the config file - needs to be done without specific paths.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        #self.load_config_path = "/home/vortex/vortex_ws/src/Vortex_CV/camera_calibration/scripts/SN38762967FACTORY_REAL_THIS_TIME_FU_BENJAMIN.conf"
Remove.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        self.objp *= 108 # Chessboard width
Parametrize board size, dimensions, checker width, height, etc.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        self.timerPub = rospy.Publisher('/feature_detection/fps_timer', Float32, queue_size= 1)
Remove.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +            self.image_shape_right = (720, 1280, 4)
Remove the error-handling, if there's an error here the program should just stop.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        # self.dynam_client = dynamic_reconfigure.client.Client("/CVOD/feature_detection_cfg", config_callback=self.dynam_reconfigure_callback)
Remove.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +                        start = timer() # Start function timer.
Remove the timer.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +                        # self.camera_callback_right(self.first_image_right_msg)
Remove if it's not used.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +                        self.timerPub.publish(fps)
Remove the timer.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +                rospy.logerr("CvBridge Error: {0}".format(e))
Refactor this to be a single function.

Documentation needed.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +
Docuementation needed.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        ############## CALIBRATION #######################################################
If you have to specify that the calibration starts here, then it would be beneficial to just split this into 2 different functions.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +            self.update_config(newCameraMatrixL, distL, newCameraMatrixR, distR, str((frameSize[1], frameSize[0])))
Are we doing anything with the stereo calibration? This either needs to be removed or moved into its own function.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        #self.calibPub.publish(left_calib_string)
Remove.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +    def update_config(self, newCameraMatrixL, distL, newCameraMatrixR, distR, resolution):
Documentation needed.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        #print("Using resolution: ", resolution)
Remove if not used.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +
Remove is not used.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +                print("It works")
Remove this?

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        except:
Do proper exception handling with specific error name.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +    def rectify_image(self):
Docmentation needed.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/camera_calibration_node.py
> +        feature_detection_node.spin()
Change the name of the node.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/cv2_calibrating.py
> +from tkinter.messagebox import NO
Remove the commented out lines.

2022-03-14 12:15 UTC, theBadMusician commented on cv_utils/scripts/stereo_calibration_tut.py
> +import numpy as np
Remove the commented out lines.

2022-03-14 12:15 UTC, theBadMusician commented on feature_detection/scripts/feature_detection_node.py
>  import numpy as np
Not calibration specific. Why is this change here? Make a new commit which reverts the changes made by the specific commit which has done these changes.

2022-03-14 12:15 UTC, theBadMusician commented on object_edc/.vscode/launch.json
> +{
Not calibration specific. Why is this change here? 

Make a new commit which reverts the changes made by the specific commit which has done these changes.

2022-03-14 12:15 UTC, theBadMusician commented on object_edc/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.2)
Not calibration specific. Revert changes.

2022-03-14 12:15 UTC, theBadMusician commented on object_edc/ReadMe.txt
> +Solutions for estimation, detection and classification of objects in the world. Separate but ralated problem to the one of state estimation, so initializing with this a new directory for it. Update t
Remove all the object edc files / file changes.

2022-03-14 12:15 UTC, theBadMusician commented on rospy/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.2)
Remove file.

2022-03-14 12:15 UTC, theBadMusician commented on rospy/package.xml
> +<?xml version="1.0"?>
Remove file.

2022-03-14 13:09 UTC, SimonVolden commented
Should be fixed now

2022-03-15 18:32 UTC, SimonVolden commented on cv_utils/scripts/stereo_calibration_tut.py
> +import numpy as np
The commented out lines can be nice to have, as they have a purpose if used. E.g. we can get cropped images, and display rectified images

2022-03-15 18:37 UTC, SimonVolden reviewed
Removed object_edc, take a look at the feature_detection folder

2022-04-23 11:24 UTC, theBadMusician commented
Closing, as this has many unexplained conflicts. The relevant changes will be merged in PR #66 .

2022-04-23 11:24 UTC, closed without merging