Feature/path following perception
vortexntnu/deprecated-vortex-cv pull request #82
Opened 2022-05-27 22:45 UTC by ivangushkov

Pretty much ready for pool test.

2022-08-29 12:57 UTC, chrstrom requested changes
Very minor comment cleanup. After that, we can merge if this worked well on the test data. @ivangushkov, what is the status on that?

2022-08-29 12:57 UTC, chrstrom commented on path_following/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.2)
Remove commented lines in this file

2022-09-04 17:18 UTC, ivangushkov commented on path_following/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.2)
Yessir!

2022-09-24 09:36 UTC, theBadMusician approved these changes
LGTM

2022-09-24 09:40 UTC, merged