Hough transform node is ready for merge with main. Adding it to the feature detection package
vortexntnu/deprecated-vortex-cv pull request #89
Opened 2022-08-07 21:40 UTC by KristianSem

2022-08-08 10:54 UTC, chrstrom requested changes
Minor cleanup.

After the cleanup, run this through an autoformatter please, like black. (python -m black *.py)

2022-08-08 10:54 UTC, chrstrom commented on feature_detection/scripts/Hough_Transform_orientation_based.py
> +class HoughMajingo_ob:
New name for this class? 🤣

2022-08-08 10:54 UTC, chrstrom commented on feature_detection/scripts/Hough_Transform_orientation_based.py
> +            ver = 0  # value for horizontal lines
Switch the meaning of "set" so we can instead do

```suggestion
        def lines_coord(lines_HT, set=0, e=8):
            ...
            if not set in [0, 1]:
                # Do something to handle this
            ver = set
```

2022-08-08 10:54 UTC, chrstrom commented on feature_detection/scripts/Hough_Transform_orientation_based.py
> +            platzhalter = np.zeros(4)
English pls

2022-08-08 10:54 UTC, chrstrom commented on feature_detection/scripts/hough_transform_node.py
> +
Remove commented out debug stuff

2022-08-08 13:32 UTC, KristianSem commented on feature_detection/scripts/Hough_Transform_orientation_based.py
> +class HoughMajingo_ob:
Majingo_ob it is ;)

2022-08-08 13:33 UTC, KristianSem commented on feature_detection/scripts/Hough_Transform_orientation_based.py
> +            ver = 0  # value for horizontal lines
Changed set to orientation, since set is a python class.
ver  = 1 - orientation, it will do the same job

2022-08-11 19:31 UTC, chrstrom requested changes

2022-08-11 19:31 UTC, chrstrom commented on feature_detection/scripts/Hough_Transform_orientation_based.py
> +        """
Make orientation a default arg?

```suggestion
    @staticmethod
    def lines_coord(lines_HT, orientation=0, e=8):
        """
```

2022-08-19 08:00 UTC, chrstrom approved these changes
LGTM 🚀

2022-08-29 12:49 UTC, merged